/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MenuItems } from "./types/menu-items";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface RhSideBar {
        "menuItems": MenuItems[];
    }
    interface RhSideBarItems {
        "menuItems": MenuItems[];
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLRhSideBarElement extends Components.RhSideBar, HTMLStencilElement {
    }
    var HTMLRhSideBarElement: {
        prototype: HTMLRhSideBarElement;
        new (): HTMLRhSideBarElement;
    };
    interface HTMLRhSideBarItemsElement extends Components.RhSideBarItems, HTMLStencilElement {
    }
    var HTMLRhSideBarItemsElement: {
        prototype: HTMLRhSideBarItemsElement;
        new (): HTMLRhSideBarItemsElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "rh-side-bar": HTMLRhSideBarElement;
        "rh-side-bar-items": HTMLRhSideBarItemsElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface RhSideBar {
        "menuItems"?: MenuItems[];
    }
    interface RhSideBarItems {
        "menuItems"?: MenuItems[];
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "rh-side-bar": RhSideBar;
        "rh-side-bar-items": RhSideBarItems;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "rh-side-bar": LocalJSX.RhSideBar & JSXBase.HTMLAttributes<HTMLRhSideBarElement>;
            "rh-side-bar-items": LocalJSX.RhSideBarItems & JSXBase.HTMLAttributes<HTMLRhSideBarItemsElement>;
        }
    }
}
